# Site settings
exclude: [README.md]
title: Wilker Aziz
email: will.aziz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Here you will find details about my work.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wilkeraziz.github.io/dcs-site/index.html" # the base hostname & protocol for your site
twitter_username: wilkeraziz
github_username:  wilkeraziz
paginate: 4

# current department
current_department: DCS
departamental_page: http://wilkeraziz.github.io/dcs-site
current_dpt_email: w.aziz@sheffield.ac.uk

# useful links
google_scholar_url: http://scholar.google.co.uk/citations?user=phgBJXYAAAAJ&hl=en
dcs_page: http://wilkeraziz.github.io/dcs-site
modist_url: http://staffwww.dcs.shef.ac.uk/people/L.Specia/projects/modist.html
lucia_specia: http://staffwww.dcs.shef.ac.uk/people/L.Specia
khalil_simaan: https://staff.fnwi.uva.nl/k.simaan/
slpll_url: https://staff.fnwi.uva.nl/k.simaan/research_all.html
uva_url: http://www.illc.uva.nl/

# Build settings
markdown: kramdown
